spring.application.name=TaskMate626SS13BuckUp5

spring.datasource.url=jdbc:postgresql://localhost:5432/dic_db1
spring.datasource.username=dic_user1
spring.datasource.password=pdic_user1
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:com/example/taskmate/repository/*.xml

logging.level.com.example.taskmate.repository=DEBUG